# Generated by Django 5.2.3 on 2025-07-13 06:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login', '0002_requirement'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('test_id', models.CharField(max_length=50)),
                ('test_name', models.CharField(max_length=200)),
                ('pre_condition', models.TextField(blank=True, null=True)),
                ('test_condition', models.TextField(blank=True, null=True)),
                ('expected_result', models.TextField()),
                ('actual_result', models.TextField(blank=True, null=True)),
                ('test_result', models.CharField(choices=[('Pass', 'Pass'), ('Fail', 'Fail'), ('Pending', 'Pending')], default='Pending', max_length=10)),
                ('version', models.DecimalField(decimal_places=1, default=1.0, max_digits=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requirement', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='testcases', to='login.requirement')),
            ],
            options={
                'unique_together': {('requirement', 'test_id')},
            },
        ),
    ]
